[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
seeds = false
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]
skip-lint = false

[programs.devnet]
hotel_coconut = "ovD3fLdpR5EGndchryCuJFx1pFZgLbdimc2ccEi2jzs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./new_program_id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"